@startuml

class Vehiculo{
   - marca : String
   + Vehiculo(marca: String)

}

class Coche extends Vehiculo{
   - numPuertas : int
   + Coche( (marca: String, numPuertas: int)
}

@enduml